blank_issues_enabled: true
contact_links:
  -name: Bug反馈
  description: 中文Bug反馈模板
  title: "[Bug]: "
  labels: [ "bug" ]

  body:
    - type: markdown
      attributes:
        value: |
          请确保您使用的是最新版的RC，您反馈的bug很可能已经在更新版本中修复
          （查看尾缀是否与最新工件相同）
          在反馈bug前，请先尝试搜索是否已有相似的问题，请不要重复打开相同的issue

          所有有关YSM的问题，请您优先寻求他人的帮助，或者观看配置模型教程
          而不是直接在issue中提问。

    - type: checkboxes
      id: preliminary
      attributes:
        label: 我已确认 ...
        options:
          - label: 我正在使用最新版的RC
            required: true
          - label: 无法在关闭主要功能时复现
            required: true

    - type: input
      id: minecraft-version
      attributes:
        label: Minecraft版本
        description: |
          你所使用的Minecraft的版本.

          你可以在游戏主界面作下角或者游戏启动时的日志开头等地方找到.
      validations:
        required: true

    - type: textarea
      id: incompatible-mods
      attributes:
        label: 不兼容的mod
        description: >-
          和bug相关的模组
          <br>请在反馈问题前尝试尽可能移除不相干的模组的情况下复现bug
        placeholder: 'Mods list here'
        render: 'raw'
      validations:
        required: true

    - type: textarea
      id: description
      attributes:
        label: 错误描述
        description: >-
          请尽可能详细的描述遇到的问题. 
          <br>越清晰和详尽的描述会使该bug的处理优先级更高
      validations:
        required: true

    - type: textarea
      id: step
      attributes:
        label: 复现步骤
        placeholder: |
          1. Join the game...

          2. Change some settings...

          3. ...

    - type: textarea
      id: logs
      attributes:
        label: 日志和崩溃报告
        description: >-
        你可以在/logs/lastest.log 和 /crash-report 中找到错误报告，或者使用启动器的导出功能
        <br>你可以日志上传到类似 https://paste.ubuntu.com/ 或者 https://mclo.gs/ 的网站并在此贴出链接
        <br>**请不要在此此处直接粘贴大段的日志文本!!**
        placeholder: '把日志文件往这丢或者使用外部链接'


  -name: Bug Report
  description: English template for reporting a bug
  title: "[Bug]: "
  labels: [ "bug" ]

  body:
    - type: markdown
      attributes:
        value: |
          Make sure you're using the latest version of RC, the bug you're reporting has most likely been fixed in the latest update
          （Check if the suffix matches the latest artifact）
          Before reporting a bug, please search for similar issues first and avoid opening duplicate issues

          For all YSM-related questions, please seek help from others or watch configuration model tutorials first
          instead of asking directly in the issue.

    - type: checkboxes
      id: preliminary
      attributes:
        label: I have confirmed that ...
        options:
          - label: I am using the latest version of RC
            required: true
          - label: Unable to reproduce when main feature is disabled
            required: true

    - type: input
      id: minecraft-version
      attributes:
        label: Minecraft Version
        description: |
          The Minecraft version you are using.

          You can find them at the corner of main menu or in the log while startup.
      validations:
        required: true

    - type: textarea
      id: incompatible-mods
      attributes:
        label: Incompatible Mods
        description: >-
          The mods related to the bug.
          <br>Try to remove unrelated plugins and mods before reporting
        placeholder: 'Mods list here'
        render: 'raw'
      validations:
        required: true

    - type: textarea
      id: description
      attributes:
        label: Bug Description
        description: >-
          Please describe the issue you encountered in as much detail as possible. 
          <br>Clearer and more detailed descriptions will receive higher processing priority
        validations:
          required: true

    - type: textarea
      id: step
      attributes:
        label: Reproduction Steps
        placeholder: |
          1. Join the game...

          2. Change some settings...

          3. ...

    - type: textarea
      id: logs
      attributes:
        label: Logs & Crash Reports
        description: >-
          You can find error reports in /logs/latest.log and /crash-reports, or use the launcher's export function
          <br>You can upload logs to sites like https://paste.ubuntu.com/ or https://mclo.gs/ and post the link here
          <br>**DO NOT PASTE LARGE LOGS DIRECTLY HERE!!**
        placeholder: 'Drag log file here or use external link'
