name: Bug反馈
description: 中文Bug反馈模板
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        请确保您使用的是最新版的RC，您反馈的bug很可能已经在更新版本中修复
        （查看尾缀是否与最新工件相同）
        在反馈bug前，请先尝试搜索是否已有相似的问题，请不要重复打开相同的issue

        所有有关YSM的问题，请您优先寻求他人的帮助，或者观看配置模型教程
        而不是直接在issue中提问。

  - type: checkboxes
    id: preliminary
    attributes:
      label: 我已确认 ...
      options:
        - label: 我正在使用最新版的RC
          required: true
        - label: 无法在关闭主要功能时复现
          required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft版本
      description: |
        你所使用的Minecraft的版本.

        你可以在游戏主界面作下角或者游戏启动时的日志开头等地方找到.
    validations:
      required: true

  - type: textarea
    id: incompatible-mods
    attributes:
      label: 不兼容的mod
      description: >-
        和bug相关的模组
        <br>请在反馈问题前尝试尽可能移除不相干的模组的情况下复现bug
      placeholder: 'Mods list here'
      render: 'raw'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 错误描述
      description: >-
        请尽可能详细的描述遇到的问题. 
        <br>越清晰和详尽的描述会使该bug的处理优先级更高
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: 复现步骤
      placeholder: |
        1. Join the game...

        2. Change some settings...

        3. ...

  - type: textarea
    id: logs
    attributes:
      label: 日志和崩溃报告
      description: >-
       你可以在/logs/lastest.log 和 /crash-report 中找到错误报告，或者使用启动器的导出功能
        <br>你可以日志上传到类似 https://paste.ubuntu.com/ 或者 https://mclo.gs/ 的网站并在此贴出链接
        <br>**请不要在此此处直接粘贴大段的日志文本!!**
      placeholder: '把日志文件往这丢或者使用外部链接'
